---
title: "QTL0001 - Ineligibilty"
---

# QTL0001 - Ineligibility

## Study Overview
```{r, echo=FALSE}
QTL_Overview(dfResults = qtl0001_params$dfResults,
             dSnapshot = qtl0001_params$latest_snapshot,
             strNum = "Ineligible Participants",
             strDenom = "Total Enrolled", 
             strQTL = "Current Ineligible Enrolled Rate")
```

## Time Series Chart
```{r, echo=FALSE, results='asis', fig.height=4}
QTL_lineplot_v2(dfResults = qtl0001_params$dfResults, strQTL = "Ineligibility Rate")
```

## Bar Charts {.tabset .tabset-pills}

```{r, eval = FALSE , echo = FALSE, results = 'asis', fig.height=4}
### JS - Site
# gsm.qtl::Widget_BarChartQTL(
#   dfResults = dfResults %>% filter(GroupLevel == "Site", SnapshotDate == latest_snapshot, GroupID != "Upper_funnel"),
#   dfGroups = dfGroups,
#   strOutcome = "Metric"
# )
```

### Site
```{r, echo = FALSE, results = 'asis', fig.height=4}
eligibility_groupBar(df = qtl0001_params$dfListing, varGroupID = invid, strGroupLabel = "Site")
```

### Country
```{r, echo = FALSE, results = 'asis', fig.height=4}
eligibility_groupBar(df = qtl0001_params$dfListing, varGroupID = country, strGroupLabel = "Country")
```

### Source
```{r, echo = FALSE, results = 'asis', fig.height=4}
eligibility_sourceBar(df = qtl0001_params$dfListing)
```

### Criteria/Site (EDC I/E data only)
```{r, echo = FALSE, results = 'asis', fig.height=4}
criteria_groupBar(df = qtl0001_params$dfListing, varGroupID = invid, strGroupLabel = "Site")
```

### Criteria/Country (EDC I/E data only)
```{r, echo = FALSE, results = 'asis', fig.height=4}
criteria_groupBar(df = qtl0001_params$dfListing, varGroupID = country, strGroupLabel = "Country")
```

### Site/Criteria (EDC I/E data only)
```{r, echo = FALSE, results = 'asis', fig.height=4}
criteria_groupBar(df = qtl0001_params$dfListing, varGroupID = invid, strGroupLabel = "Site", bSwapAxes = TRUE)
```

### Country/Criteria (EDC I/E data only)
```{r, echo = FALSE, results = 'asis', fig.height=4}
criteria_groupBar(df = qtl0001_params$dfListing, varGroupID = country, strGroupLabel = "Country", bSwapAxes = TRUE)
```

## Inclusion/Exclusion Listing
```{r, echo = FALSE}
# output the listing on the html
eligibility_listing(df = qtl0001_params$dfListing)

# grab the dataset to download
x <- eligibility_listing(df = qtl0001_params$dfListing, download = TRUE)
csv_txt <- paste(capture.output(write.csv(x, row.names = FALSE)), collapse = "\n")# turn into a data-URI (single-file HTML friendly)
href <- base64enc::dataURI(charToRaw(csv_txt), mime = "text/csv;charset=utf-8")

knitr::asis_output(
  sprintf('<p><a class="btn btn-primary" download="eligibility_listing.csv" href="%s">
            â¬‡ď¸Ź Download CSV
          </a></p>', href)
)
```
