---
title: "QTL0002 - Premature Study Discontinuation"
---

# QTL0002 - Premature Study Discontinuation

## Study Overview
```{r, echo=FALSE}
gsm.qtl::QTL_Overview(dfResults = qtl0002_params$dfResults,
             dSnapshot = qtl0002_params$latest_snapshot,
             strNum = "Participants Discontinued - Study",
             strDenom = "Total Enrolled", 
             strQTL = "Current Premature Discontinuation Rate")
```

## Time Series Chart
```{r, echo=FALSE, results='asis', fig.height=4}
gsm.qtl::QTL_lineplot_v2(dfResults = qtl0002_params$dfResults, strQTL = "Premature Discontinuation Rate")
```

## Bar Charts {.tabset .tabset-pills}

### Site
```{r, echo = FALSE, results = 'asis', fig.height=4}
<<<<<<< fix-90-namespace-report-functions
gsm.qtl::discontinuation_groupBar(df = qtl0002_params$dfListing, varGroupID = invid, strGroupLabel = "Site")
=======
discontinuation_groupBar(dfNum = qtl0002_params$dfNum, dfDenom = qtl0002_params$dfDenom, varGroupID = invid, strGroupLabel = "Site")
>>>>>>> fix-90
```

### Country
```{r, echo = FALSE, results = 'asis', fig.height=4}
<<<<<<< fix-90-namespace-report-functions
gsm.qtl::discontinuation_groupBar(df = qtl0002_params$dfListing, varGroupID = country, strGroupLabel = "Country")
=======
discontinuation_groupBar(dfNum = qtl0002_params$dfNum, dfDenom = qtl0002_params$dfDenom, varGroupID = country, strGroupLabel = "Country")
>>>>>>> fix-90
```

### Reasons
```{r, echo = FALSE, results = 'asis', fig.height=4}
<<<<<<< fix-90-namespace-report-functions
gsm.qtl::discontinuation_reasonBar(df = qtl0002_params$dfListing, varCompreas = compreas)
=======
discontinuation_reasonBar(df = qtl0002_params$dfNum, varCompreas = compreas)
>>>>>>> fix-90
```

### Reasons/Site
```{r, echo = FALSE, results = 'asis', fig.height=4}
<<<<<<< fix-90-namespace-report-functions
gsm.qtl::reasons_groupBar(df = qtl0002_params$dfListing, varGroupID = invid, varCompreas = compreas, strGroupLabel = "Site")
=======
reasons_groupBar(df = qtl0002_params$dfNum, varGroupID = invid, varCompreas = compreas, strGroupLabel = "Site")
>>>>>>> fix-90
```

### Reasons/Country
```{r, echo = FALSE, results = 'asis', fig.height=4}
<<<<<<< fix-90-namespace-report-functions
gsm.qtl::reasons_groupBar(df = qtl0002_params$dfListing, varGroupID = country, varCompreas = compreas, strGroupLabel = "Country")
=======
reasons_groupBar(df = qtl0002_params$dfNum, varGroupID = country, varCompreas = compreas, strGroupLabel = "Country")
>>>>>>> fix-90
```

### Site/Reasons
```{r, echo = FALSE, results = 'asis', fig.height=4}
<<<<<<< fix-90-namespace-report-functions
gsm.qtl::reasons_groupBar(df = qtl0002_params$dfListing, varGroupID = invid, varCompreas = compreas, strGroupLabel = "Site", bSwapAxes = TRUE)
=======
reasons_groupBar(df = qtl0002_params$dfNum, varGroupID = invid, varCompreas = compreas, strGroupLabel = "Site", bSwapAxes = TRUE)
>>>>>>> fix-90
```

### Country/Reasons
```{r, echo = FALSE, results = 'asis', fig.height=4}
<<<<<<< fix-90-namespace-report-functions
gsm.qtl::reasons_groupBar(df = qtl0002_params$dfListing, varGroupID = country, varCompreas = compreas, strGroupLabel = "Country", bSwapAxes = TRUE)
=======
reasons_groupBar(df = qtl0002_params$dfNum, varGroupID = country, varCompreas = compreas, strGroupLabel = "Country", bSwapAxes = TRUE)
>>>>>>> fix-90
```

## Discontinuation Listing
```{r, echo = FALSE}
<<<<<<< fix-90-namespace-report-functions
discontinuation_listing <- dplyr::rename(
  dplyr::select(
    dplyr::filter(qtl0002_params$dfListing, compyn %in% c("N")),
    country,
    invid,
    subjid,
    compreas
  ),
  Country = country,
  `Site ID` = invid,
  `Participant ID` = subjid,
  `Discontinuation Reason` = compreas
)
=======
discontinuation_listing <- qtl0002_params$dfNum %>%
  select(country, invid, subjid, compreas) %>%
  rename(
    Country = country,
    `Site ID` = invid,
    `Participant ID` = subjid,
    `Discontinuation Reason` = compreas
  )
>>>>>>> fix-90

# output the listing in the html
gsm.qtl::scrollable_gt(
  gt::gt(discontinuation_listing),
  height = "500px",
  min_table_width = "100px"
)

# prepare the download
csv_txt <- paste(utils::capture.output(utils::write.csv(discontinuation_listing, row.names = FALSE)), collapse = "\n")# turn into a data-URI (single-file HTML friendly)
href <- base64enc::dataURI(charToRaw(csv_txt), mime = "text/csv;charset=utf-8")

knitr::asis_output(
  sprintf('<p><a class="btn btn-primary" download="discontinuation_listing.csv" href="%s">
            ⬇️ Download CSV
          </a></p>', href)
)
```
