---
title: "Qualification Report"
date: "Report Run Date: `r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true
vignette: >
  %\VignetteIndexEntry{Qualification}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown_notangle}
---

```{r setup, echo=FALSE, warning=FALSE}
suppressPackageStartupMessages({
  library(gsm.core)
  library(gt)
  library(knitr)
  library(dplyr)
  library(purrr)
  library(pander)
  library(gh)
  library(stringr)
  library(riskmetric)
  suppressMessages(devtools::load_all())
})

opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = TRUE,
  echo = FALSE,
  results = "asis",
  message = FALSE,
  tidy = FALSE
)

source(here::here("inst", "qualification", "specs.R"))
source(here::here("inst", "qualification", "test_cases.R"))
spec_df <- import_specs()
```
```{r}
spec_list <- list.files(here::here('tests', 'testqualification', 'qualification'), pattern = "test-qual_", full.names = TRUE)

scrape <- map_df(spec_list, function(x) {
    testResultsRaw <- testthat::test_file(x, reporter = testthat::ListReporter, package = "gsm.qtl") %>%
      as_tibble()

    return(testResultsRaw)
}) %>%
  mutate(Tests = gsub("test-qual_", "", file),
         Tests = gsub(".R", "", Tests))

funcs <- spec_df %>%
  select(Tests, Assessment) %>%
  tidyr::separate_rows("Tests", sep = ",") %>%
  mutate(Tests = trimws(Tests)) %>%
  rename(Function = Assessment) %>%
  distinct()

testResultsIndividual <- left_join(scrape, funcs, by = "Tests") %>%
  group_by(Function) %>%
  reframe(`Function Name` = unique(Function),
          `Number of Tests` = sum(nb),
          `Number Passed` = sum(passed),
          `Number Failed` = sum(failed),
          `Number Skipped` = sum(skipped)) %>%
  arrange(`Function Name`) %>%
  select(-Function)

scrape_new <- left_join(scrape, funcs, by = "Tests")

qual_specs_orig <- read.csv(system.file("qualification", "qualification_specs.csv", package = "gsm.qtl"))
qual_specs <- qual_specs_orig %>%
  mutate(SpecID = paste0("S", Spec, "_", Test.ID)) %>%
  select(Specs = SpecID, Tests, N.Tests)

### One row per spec
Specifications <- spec_df %>%
  select(ID, Description, Risk, Impact, Tests) %>%
  mutate(sort1 = as.numeric(str_extract(ID, "(?<=S)\\d+")),
         sort2 = as.numeric(str_extract(ID, "\\d+$"))) %>%
  arrange(as.numeric(sort1), as.numeric(sort2)) %>%
  select(-c(sort1, sort2))
colnames(Specifications) <- c("Spec ID", "Spec Description", "Risk", "Impact", "Associated Test IDs")

Specifications %>%
  gt() %>%
  tab_options(
    latex.use_longtable = T,
    table.font.size = px(9)
  )%>%
  cols_width(
    `Spec Description` ~ px(180),
    `Associated Test IDs` ~ px(150)
  ) %>%
  opt_row_striping()
```

\newpage

## One Row Per Test

```{r}
### One row per test
 test <- scrape_new %>%
  mutate(result_new = ifelse(failed == 0, "Pass", "Fail")) %>%
  select(Tests, test, result_new, Function)

Results <- left_join(test, qual_specs, by = "Tests") %>%
  select(Function, Specs, Tests, test, result_new) %>%
  mutate(sort1 = as.numeric(str_extract(Tests, "(?<=T)\\d+")),
         sort2 = as.numeric(str_extract(Tests, "\\d+$"))) %>%
  arrange(as.numeric(sort1), as.numeric(sort2)) %>%
  select(-c(sort1, sort2))
colnames(Results) <- c("Function", "Spec ID", "Test ID", "Test Description", "Test Result")

Results %>%
  gt() %>%
  tab_options(
    latex.use_longtable = T,
    table.font.size = px(9)
  ) %>%
  cols_width(
    `Function` ~ px(120),
    `Spec ID` ~ px(90),
    `Test Description` ~ px(180)
  ) %>%
  opt_row_striping()
```

\newpage
